output.logstash:
  hosts: ["localhost:5044"]
  ssl.certificate_authorities: ["/root/elk_filebeats.crt"]
  ssl.certificate: "/root/elk_filebeats.crt"
  ssl.key: "/root/elk_filebeats.key"

filebeat.prospectors:
    -
      paths:
        - "/tmp/error.json"
      input_type: log
      fields:
        app: mon
        log: error
