elk:
  build: .
  container_name: "elk"
  volumes:
    - ./conf.d:/etc/logstash/conf.d
    - ./patterns:/etc/logstash/patterns
    - ./jvm.options:/etc/elasticsearch/jvm.options
    - ./certs/elk_filebeats.crt:/etc/pki/tls/certs/elk_filebeats.crt
    - ./certs/elk_filebeats.key:/etc/pki/tls/private/elk_filebeats.key
    - ./kibana.yml:/opt/kibana/config/kibana.yml
    - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
